### ISSUE TITLE
a type containing a comma is treated as multiple arguments

### ISSUE THREAD

**Issue by m59peacemaker** [Geode-solutions/genepi#18]
There are meant to be 4 arguments to `GENEPI_MULTIMETHOD` here, `name, type, new_name, first_arg`.

```c++
GENEPI_MULTIMETHOD(classify, std::pair<int,float>, "classify_0", InputArray);
```

The comma in the return type, `std::pair<int,float>`, seems to be treated as two arguments: `std::pair<int` and `float>`, causing an error.

```
error: wrong number of template arguments (3, should be 2)
  859 |         GENEPI_MULTIMETHOD(classify, std::pair<int,float>, "classify_0", InputArray);
```

**Comment by BotellaA** [comment]
This is an issue with the c++ macro itself... Here is an example of solution https://stackoverflow.com/questions/13842468/comma-in-c-c-macro.

**Comment by m59peacemaker** [comment]
This solution from that post worked out best for me.

```c++
#define COMMA ,

GENEPI_MULTIMETHOD(classify, std::pair<int COMMA float>, "classify_0", InputArray);
```

Thanks!
